// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsim.h for the primary calling header

#ifndef VERILATED_VSIM_VEXRISCV_H_
#define VERILATED_VSIM_VEXRISCV_H_  // guard

#include "verilated.h"


class Vsim__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsim_VexRiscv final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__timerInterrupt,0,0);
        VL_IN8(__PVT__softwareInterrupt,0,0);
        VL_OUT8(__PVT__iBusWishbone_CYC,0,0);
        VL_OUT8(__PVT__iBusWishbone_STB,0,0);
        VL_IN8(__PVT__iBusWishbone_ACK,0,0);
        VL_OUT8(__PVT__iBusWishbone_WE,0,0);
        VL_OUT8(__PVT__iBusWishbone_SEL,3,0);
        VL_IN8(__PVT__iBusWishbone_ERR,0,0);
        VL_OUT8(__PVT__iBusWishbone_CTI,2,0);
        VL_OUT8(__PVT__iBusWishbone_BTE,1,0);
        VL_OUT8(__PVT__dBusWishbone_CYC,0,0);
        VL_OUT8(__PVT__dBusWishbone_STB,0,0);
        VL_IN8(__PVT__dBusWishbone_ACK,0,0);
        VL_OUT8(__PVT__dBusWishbone_WE,0,0);
        VL_OUT8(__PVT__dBusWishbone_SEL,3,0);
        VL_IN8(__PVT__dBusWishbone_ERR,0,0);
        VL_OUT8(__PVT__dBusWishbone_CTI,2,0);
        VL_OUT8(__PVT__dBusWishbone_BTE,1,0);
        VL_IN8(__PVT__reset,0,0);
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_flush;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_cpu_prefetch_isValid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_cpu_fetch_isRemoved;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_cpu_decode_isValid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_cpu_fill_valid;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_execute_isValid;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_isValid;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_SW;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_SR;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_SO;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_SI;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_PW;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_PR;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_PO;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_PI;
        CData/*3:0*/ __PVT__dataCache_1_io_cpu_writeBack_fence_FM;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_flush_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_cpu_prefetch_haltIt;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache_io_mem_cmd_valid;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_haltIt;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_mmuException;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_unalignedAccess;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_accessError;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writeBack_exclusiveOk;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_flush_ready;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_redo;
        CData/*0:0*/ __PVT__dataCache_1_io_cpu_writesPending;
        CData/*0:0*/ __PVT__dataCache_1_io_mem_cmd_valid;
        CData/*0:0*/ __PVT__dataCache_1_io_mem_cmd_payload_wr;
        CData/*2:0*/ __PVT__dataCache_1_io_mem_cmd_payload_size;
        CData/*1:0*/ __PVT___zz_IBusCachedPlugin_jump_pcLoad_payload_6;
        CData/*7:0*/ __PVT___zz_writeBack_DBusCachedPlugin_rspShifted;
        CData/*7:0*/ __PVT___zz_writeBack_DBusCachedPlugin_rspShifted_2;
        CData/*0:0*/ __PVT___zz___05Fzz_decode_IS_RS2_SIGNED_68;
        CData/*2:0*/ __PVT___zz___05Fzz_decode_IS_RS2_SIGNED_121;
        CData/*0:0*/ __PVT__decode_PREDICTION_HAD_BRANCHED2;
        CData/*1:0*/ __PVT__decode_ENV_CTRL;
        CData/*0:0*/ __PVT__decode_IS_CSR;
        CData/*0:0*/ __PVT__decode_SRC_LESS_UNSIGNED;
        CData/*0:0*/ __PVT__decode_BYPASSABLE_MEMORY_STAGE;
        CData/*0:0*/ __PVT__decode_BYPASSABLE_EXECUTE_STAGE;
        CData/*0:0*/ __PVT__execute_BRANCH_COND_RESULT;
        CData/*0:0*/ __PVT__decode_RS2_USE;
        CData/*0:0*/ __PVT__decode_RS1_USE;
    };
    struct {
        CData/*0:0*/ __PVT__decode_SRC_USE_SUB_LESS;
        CData/*0:0*/ __PVT__execute_SRC_LESS;
        CData/*0:0*/ __PVT__decode_LEGAL_INSTRUCTION;
        CData/*0:0*/ __PVT__IBusCachedPlugin_rsp_issueDetected_3;
        CData/*0:0*/ __PVT__IBusCachedPlugin_rsp_issueDetected_1;
        CData/*0:0*/ __PVT__decode_arbitration_haltByOther;
        CData/*0:0*/ __PVT__decode_arbitration_removeIt;
        CData/*0:0*/ __PVT__decode_arbitration_flushNext;
        CData/*0:0*/ __PVT__decode_arbitration_isValid;
        CData/*0:0*/ __PVT__decode_arbitration_isStuck;
        CData/*0:0*/ __PVT__decode_arbitration_isFlushed;
        CData/*0:0*/ __PVT__decode_arbitration_isMoving;
        CData/*0:0*/ __PVT__execute_arbitration_haltItself;
        CData/*0:0*/ __PVT__execute_arbitration_removeIt;
        CData/*0:0*/ __PVT__execute_arbitration_flushNext;
        CData/*0:0*/ __PVT__execute_arbitration_isValid;
        CData/*0:0*/ __PVT__execute_arbitration_isStuck;
        CData/*0:0*/ __PVT__execute_arbitration_isFlushed;
        CData/*0:0*/ __PVT__execute_arbitration_isMoving;
        CData/*0:0*/ __PVT__memory_arbitration_haltItself;
        CData/*0:0*/ __PVT__memory_arbitration_removeIt;
        CData/*0:0*/ __PVT__memory_arbitration_flushNext;
        CData/*0:0*/ __PVT__memory_arbitration_isValid;
        CData/*0:0*/ __PVT__memory_arbitration_isStuck;
        CData/*0:0*/ __PVT__memory_arbitration_isStuckByOthers;
        CData/*0:0*/ __PVT__memory_arbitration_isFlushed;
        CData/*0:0*/ __PVT__memory_arbitration_isMoving;
        CData/*0:0*/ __PVT__writeBack_arbitration_removeIt;
        CData/*0:0*/ __PVT__writeBack_arbitration_flushNext;
        CData/*0:0*/ __PVT__writeBack_arbitration_isValid;
        CData/*0:0*/ lastStageIsValid;
        CData/*0:0*/ lastStageIsFiring;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetcherHalt;
        CData/*0:0*/ __PVT__IBusCachedPlugin_predictionJumpInterface_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_decodePrediction_rsp_wasWrong;
        CData/*0:0*/ __PVT__IBusCachedPlugin_decodeExceptionPort_valid;
        CData/*3:0*/ __PVT__IBusCachedPlugin_decodeExceptionPort_payload_code;
        CData/*0:0*/ __PVT__IBusCachedPlugin_mmuBus_rsp_bypassTranslation;
        CData/*0:0*/ __PVT__dBus_rsp_payload_last;
        CData/*0:0*/ __PVT__DBusCachedPlugin_mmuBus_rsp_bypassTranslation;
        CData/*0:0*/ __PVT__DBusCachedPlugin_redoBranch_valid;
        CData/*0:0*/ __PVT__DBusCachedPlugin_exceptionBus_valid;
        CData/*3:0*/ __PVT__DBusCachedPlugin_exceptionBus_payload_code;
        CData/*0:0*/ __PVT__BranchPlugin_branchExceptionPort_valid;
        CData/*0:0*/ __PVT__CsrPlugin_csrMapping_allowCsrSignal;
        CData/*0:0*/ CsrPlugin_inWfi;
        CData/*0:0*/ __PVT__CsrPlugin_jumpInterface_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_jump_pcLoad_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_output_ready;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_correction;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_correctionReg;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_output_fire;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_pcRegPropagate;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_booted;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_inc;
        CData/*0:0*/ __PVT__when_Fetcher_l133;
        CData/*0:0*/ __PVT__IBusCachedPlugin_fetchPc_flushed;
        CData/*0:0*/ __PVT___zz_IBusCachedPlugin_iBusRsp_stages_2_input_ready;
        CData/*0:0*/ __PVT__IBusCachedPlugin_iBusRsp_flush;
        CData/*0:0*/ __PVT___zz_IBusCachedPlugin_iBusRsp_stages_1_input_valid_1;
        CData/*0:0*/ __PVT___zz_IBusCachedPlugin_iBusRsp_stages_1_output_m2sPipe_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_iBusRsp_output_payload_rsp_error;
        CData/*0:0*/ __PVT__IBusCachedPlugin_iBusRsp_output_payload_isRvc;
        CData/*0:0*/ __PVT__IBusCachedPlugin_injector_nextPcCalc_valids_0;
    };
    struct {
        CData/*0:0*/ __PVT__IBusCachedPlugin_injector_nextPcCalc_valids_1;
        CData/*0:0*/ __PVT__IBusCachedPlugin_injector_nextPcCalc_valids_2;
        CData/*0:0*/ __PVT__IBusCachedPlugin_injector_nextPcCalc_valids_3;
        CData/*0:0*/ __PVT__IBusCachedPlugin_injector_nextPcCalc_valids_4;
        CData/*0:0*/ __PVT__IBusCachedPlugin_s1_tightlyCoupledHit;
        CData/*0:0*/ __PVT__IBusCachedPlugin_s2_tightlyCoupledHit;
        CData/*0:0*/ __PVT__IBusCachedPlugin_rsp_redoFetch;
        CData/*0:0*/ __PVT__when_IBusCachedPlugin_l250;
        CData/*0:0*/ __PVT__when_IBusCachedPlugin_l256;
        CData/*0:0*/ __PVT__when_IBusCachedPlugin_l262;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_ready;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rValidN;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_wr;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_uncached;
        CData/*3:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_mask;
        CData/*2:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_size;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_last;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rValid;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_wr;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_uncached;
        CData/*3:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_mask;
        CData/*2:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_size;
        CData/*0:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_last;
        CData/*0:0*/ lastStageRegFileWrite_valid;
        CData/*4:0*/ lastStageRegFileWrite_payload_address;
        CData/*0:0*/ __PVT___zz_10;
        CData/*0:0*/ __PVT__HazardSimplePlugin_src0Hazard;
        CData/*0:0*/ __PVT__HazardSimplePlugin_src1Hazard;
        CData/*0:0*/ __PVT__HazardSimplePlugin_writeBackWrites_valid;
        CData/*0:0*/ __PVT__HazardSimplePlugin_writeBackBuffer_valid;
        CData/*4:0*/ __PVT__HazardSimplePlugin_writeBackBuffer_payload_address;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l45;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l48_1;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l51_1;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l45_1;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l48_2;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l51_2;
        CData/*0:0*/ __PVT__when_HazardSimplePlugin_l45_2;
        CData/*0:0*/ __PVT__execute_BranchPlugin_eq;
        CData/*1:0*/ __PVT__CsrPlugin_mtvec_mode;
        CData/*0:0*/ __PVT__CsrPlugin_mstatus_MIE;
        CData/*0:0*/ __PVT__CsrPlugin_mstatus_MPIE;
        CData/*1:0*/ __PVT__CsrPlugin_mstatus_MPP;
        CData/*0:0*/ __PVT__CsrPlugin_mip_MEIP;
        CData/*0:0*/ __PVT__CsrPlugin_mip_MTIP;
        CData/*0:0*/ __PVT__CsrPlugin_mip_MSIP;
        CData/*0:0*/ __PVT__CsrPlugin_mie_MEIE;
        CData/*0:0*/ __PVT__CsrPlugin_mie_MTIE;
        CData/*0:0*/ __PVT__CsrPlugin_mie_MSIE;
        CData/*0:0*/ __PVT__CsrPlugin_mcause_interrupt;
        CData/*3:0*/ __PVT__CsrPlugin_mcause_exceptionCode;
        CData/*0:0*/ __PVT___zz_when_CsrPlugin_l1302;
        CData/*0:0*/ __PVT___zz_when_CsrPlugin_l1302_1;
        CData/*0:0*/ __PVT___zz_when_CsrPlugin_l1302_2;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValids_decode;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValids_execute;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValids_memory;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValids_writeBack;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValidsRegs_decode;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValidsRegs_execute;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValidsRegs_memory;
        CData/*0:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionValidsRegs_writeBack;
        CData/*3:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionContext_code;
        CData/*1:0*/ __PVT___zz_CsrPlugin_exceptionPortCtrl_exceptionContext_code;
    };
    struct {
        CData/*0:0*/ __PVT___zz_CsrPlugin_exceptionPortCtrl_exceptionContext_code_1;
        CData/*0:0*/ __PVT__CsrPlugin_interrupt_valid;
        CData/*3:0*/ CsrPlugin_interrupt_code;
        CData/*1:0*/ __PVT__CsrPlugin_interrupt_targetPrivilege;
        CData/*0:0*/ __PVT__CsrPlugin_pipelineLiberator_pcValids_0;
        CData/*0:0*/ __PVT__CsrPlugin_pipelineLiberator_pcValids_1;
        CData/*0:0*/ __PVT__CsrPlugin_pipelineLiberator_pcValids_2;
        CData/*0:0*/ __PVT__CsrPlugin_pipelineLiberator_active;
        CData/*0:0*/ __PVT__when_CsrPlugin_l1340;
        CData/*0:0*/ __PVT__CsrPlugin_pipelineLiberator_done;
        CData/*0:0*/ CsrPlugin_interruptJump;
        CData/*0:0*/ CsrPlugin_hadException;
        CData/*1:0*/ __PVT__CsrPlugin_targetPrivilege;
        CData/*0:0*/ __PVT__when_CsrPlugin_l1390;
        CData/*0:0*/ __PVT__when_CsrPlugin_l1456;
        CData/*0:0*/ __PVT__execute_CsrPlugin_wfiWake;
        CData/*0:0*/ __PVT__execute_CsrPlugin_illegalAccess;
        CData/*0:0*/ __PVT__execute_CsrPlugin_writeInstruction;
        CData/*0:0*/ __PVT__execute_CsrPlugin_writeEnable;
        CData/*0:0*/ __PVT__when_CsrPlugin_l1587;
        CData/*0:0*/ __PVT__memory_DivPlugin_div_needRevert;
        CData/*0:0*/ __PVT__memory_DivPlugin_div_counter_willIncrement;
        CData/*5:0*/ __PVT__memory_DivPlugin_div_counter_valueNext;
        CData/*5:0*/ __PVT__memory_DivPlugin_div_counter_value;
        CData/*0:0*/ __PVT__memory_DivPlugin_div_done;
        CData/*0:0*/ __PVT__when_MulDivIterativePlugin_l128;
        CData/*0:0*/ __PVT___zz_memory_DivPlugin_rs2;
        CData/*0:0*/ __PVT___zz_memory_DivPlugin_rs1;
        CData/*0:0*/ __PVT__decode_to_execute_MEMORY_FORCE_CONSTISTENCY;
        CData/*1:0*/ __PVT__decode_to_execute_SRC1_CTRL;
        CData/*0:0*/ __PVT__decode_to_execute_SRC_USE_SUB_LESS;
        CData/*0:0*/ __PVT__decode_to_execute_MEMORY_ENABLE;
        CData/*0:0*/ __PVT__execute_to_memory_MEMORY_ENABLE;
        CData/*0:0*/ __PVT__memory_to_writeBack_MEMORY_ENABLE;
        CData/*1:0*/ __PVT__decode_to_execute_ALU_CTRL;
        CData/*1:0*/ __PVT__decode_to_execute_SRC2_CTRL;
        CData/*0:0*/ __PVT__decode_to_execute_REGFILE_WRITE_VALID;
        CData/*0:0*/ __PVT__execute_to_memory_REGFILE_WRITE_VALID;
        CData/*0:0*/ __PVT__memory_to_writeBack_REGFILE_WRITE_VALID;
        CData/*0:0*/ __PVT__decode_to_execute_BYPASSABLE_EXECUTE_STAGE;
        CData/*0:0*/ __PVT__decode_to_execute_BYPASSABLE_MEMORY_STAGE;
        CData/*0:0*/ __PVT__execute_to_memory_BYPASSABLE_MEMORY_STAGE;
        CData/*0:0*/ __PVT__decode_to_execute_MEMORY_WR;
        CData/*0:0*/ __PVT__execute_to_memory_MEMORY_WR;
        CData/*0:0*/ __PVT__memory_to_writeBack_MEMORY_WR;
        CData/*0:0*/ __PVT__decode_to_execute_MEMORY_MANAGMENT;
        CData/*0:0*/ __PVT__decode_to_execute_SRC_LESS_UNSIGNED;
        CData/*1:0*/ __PVT__decode_to_execute_ALU_BITWISE_CTRL;
        CData/*1:0*/ __PVT__decode_to_execute_SHIFT_CTRL;
        CData/*1:0*/ __PVT__execute_to_memory_SHIFT_CTRL;
        CData/*1:0*/ __PVT__decode_to_execute_BRANCH_CTRL;
        CData/*0:0*/ __PVT__decode_to_execute_IS_CSR;
        CData/*1:0*/ __PVT__decode_to_execute_ENV_CTRL;
        CData/*1:0*/ __PVT__execute_to_memory_ENV_CTRL;
        CData/*1:0*/ __PVT__memory_to_writeBack_ENV_CTRL;
        CData/*0:0*/ __PVT__decode_to_execute_IS_MUL;
        CData/*0:0*/ __PVT__execute_to_memory_IS_MUL;
        CData/*0:0*/ __PVT__memory_to_writeBack_IS_MUL;
        CData/*0:0*/ __PVT__decode_to_execute_IS_DIV;
        CData/*0:0*/ __PVT__execute_to_memory_IS_DIV;
        CData/*0:0*/ __PVT__decode_to_execute_IS_RS1_SIGNED;
        CData/*0:0*/ __PVT__decode_to_execute_IS_RS2_SIGNED;
        CData/*0:0*/ __PVT__decode_to_execute_SRC2_FORCE_ZERO;
        CData/*0:0*/ __PVT__decode_to_execute_PREDICTION_HAD_BRANCHED2;
    };
    struct {
        CData/*0:0*/ __PVT__decode_to_execute_CSR_WRITE_OPCODE;
        CData/*0:0*/ __PVT__decode_to_execute_CSR_READ_OPCODE;
        CData/*0:0*/ __PVT__execute_to_memory_BRANCH_DO;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_3264;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_768;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_836;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_772;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_773;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_833;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_834;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_835;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_3008;
        CData/*0:0*/ __PVT__execute_CsrPlugin_csr_4032;
        CData/*2:0*/ __PVT___zz_iBusWishbone_ADR;
        CData/*0:0*/ __PVT___zz_iBus_rsp_valid;
        CData/*2:0*/ __PVT___zz_dBusWishbone_ADR;
        CData/*0:0*/ __PVT___zz_dBus_cmd_ready;
        CData/*0:0*/ __PVT___zz_dBus_cmd_ready_2;
        CData/*0:0*/ __PVT___zz_dBus_rsp_valid;
        CData/*0:0*/ __VdfgRegularize_h1463825b_0_29;
        CData/*7:0*/ __VdfgRegularize_h1463825b_0_33;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_fire;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_hadError;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_flushPending;
        CData/*7:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_flushCounter;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT___zz_when_InstructionCache_l342;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__when_InstructionCache_l351;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_cmdSent;
        CData/*2:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_wordIndex;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_write_tag_0_payload_data_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_isIoAccess;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_isPaging;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_allowRead;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_allowWrite;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_allowExecute;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_exception;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_refilling;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_bypassTranslation;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_hit_valid;
        CData/*0:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_hit_error;
        CData/*0:0*/ IBusCachedPlugin_cache__DOT____VdfgRegularize_h7c702150_0_0;
        CData/*1:0*/ __PVT__dataCache_1__DOT___zz_loader_waysAllocator;
        CData/*0:0*/ __PVT__dataCache_1__DOT___zz_1;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsReadCmd_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_payload_way;
        CData/*6:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_payload_address;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_payload_data_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_payload_data_error;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_payload_way;
        CData/*6:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_payload_address;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_payload_data_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_payload_data_error;
        CData/*0:0*/ __PVT__dataCache_1__DOT__dataWriteCmd_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__dataWriteCmd_payload_way;
        CData/*3:0*/ __PVT__dataCache_1__DOT__dataWriteCmd_payload_mask;
        CData/*0:0*/ __PVT__dataCache_1__DOT___zz_ways_0_tagsReadRsp_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__memCmdSent;
        CData/*3:0*/ __PVT__dataCache_1__DOT___zz_stage0_mask;
        CData/*3:0*/ __PVT__dataCache_1__DOT__stage0_mask;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageA_request_wr;
        CData/*1:0*/ __PVT__dataCache_1__DOT__stageA_request_size;
    };
    struct {
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageA_request_totalyConsistent;
        CData/*3:0*/ __PVT__dataCache_1__DOT__stageA_mask;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageA_wayInvalidate;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stage0_dataColisions_regNextWhen;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_request_wr;
        CData/*1:0*/ __PVT__dataCache_1__DOT__stageB_request_size;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_request_totalyConsistent;
        CData/*0:0*/ __PVT__dataCache_1__DOT__when_DataCache_l829;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_isIoAccess;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_isPaging;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_allowRead;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_allowWrite;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_allowExecute;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_exception;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_refilling;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_bypassTranslation;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_tagsReadRsp_0_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_tagsReadRsp_0_error;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_wayInvalidate;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_dataColisions;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_unaligned;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_waysHitsBeforeInvalidate;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_waysHits;
        CData/*3:0*/ __PVT__dataCache_1__DOT__stageB_mask;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_loaderValid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_flusher_waitDone;
        CData/*7:0*/ __PVT__dataCache_1__DOT__stageB_flusher_counter;
        CData/*0:0*/ __PVT__dataCache_1__DOT__when_DataCache_l863;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_flusher_start;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_cpuWriteToCache;
        CData/*0:0*/ __PVT__dataCache_1__DOT__stageB_loadStoreFault;
        CData/*0:0*/ __PVT__dataCache_1__DOT__when_DataCache_l1009;
        CData/*0:0*/ __PVT__dataCache_1__DOT__when_DataCache_l1072;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_valid;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_counter_willIncrement;
        CData/*2:0*/ __PVT__dataCache_1__DOT__loader_counter_valueNext;
        CData/*2:0*/ __PVT__dataCache_1__DOT__loader_counter_value;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_counter_willOverflow;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_waysAllocator;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_error;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_killReg;
        CData/*0:0*/ __PVT__dataCache_1__DOT__when_DataCache_l1125;
        CData/*0:0*/ __PVT__dataCache_1__DOT__loader_valid_regNext;
        CData/*7:0*/ __PVT__dataCache_1__DOT___zz_ways_0_datasymbol_read;
        CData/*7:0*/ __PVT__dataCache_1__DOT___zz_ways_0_datasymbol_read_1;
        CData/*7:0*/ __PVT__dataCache_1__DOT___zz_ways_0_datasymbol_read_2;
        CData/*7:0*/ __PVT__dataCache_1__DOT___zz_ways_0_datasymbol_read_3;
        CData/*0:0*/ dataCache_1__DOT____VdfgRegularize_h4c3f712f_0_0;
        CData/*2:0*/ __Vdly___zz_dBusWishbone_ADR;
        CData/*2:0*/ __Vdly___zz_iBusWishbone_ADR;
        CData/*0:0*/ __Vdly__CsrPlugin_mstatus_MPIE;
        CData/*2:0*/ __Vdly__IBusCachedPlugin_cache__DOT__lineLoader_wordIndex;
        CData/*7:0*/ __Vdly__IBusCachedPlugin_cache__DOT__lineLoader_flushCounter;
        CData/*0:0*/ __Vdly__dataCache_1__DOT__stageB_flusher_waitDone;
        CData/*7:0*/ __Vdly__dataCache_1__DOT__stageB_flusher_counter;
        CData/*0:0*/ __Vdly__dataCache_1__DOT__stageB_flusher_start;
        CData/*0:0*/ __Vdly__dataCache_1__DOT__loader_error;
        CData/*4:0*/ __VdlyDim0__RegFilePlugin_regFile__v0;
        CData/*0:0*/ __VdlySet__RegFilePlugin_regFile__v0;
        CData/*0:0*/ __VdlySet__IBusCachedPlugin_cache__DOT__banks_0__v0;
        CData/*6:0*/ __VdlyDim0__IBusCachedPlugin_cache__DOT__ways_0_tags__v0;
        CData/*0:0*/ __VdlySet__IBusCachedPlugin_cache__DOT__ways_0_tags__v0;
        CData/*6:0*/ __VdlyDim0__dataCache_1__DOT__ways_0_tags__v0;
        CData/*0:0*/ __VdlySet__dataCache_1__DOT__ways_0_tags__v0;
    };
    struct {
        CData/*7:0*/ __VdlyVal__dataCache_1__DOT__ways_0_data_symbol2__v0;
        CData/*0:0*/ __VdlySet__dataCache_1__DOT__ways_0_data_symbol2__v0;
        CData/*7:0*/ __VdlyVal__dataCache_1__DOT__ways_0_data_symbol0__v0;
        CData/*0:0*/ __VdlySet__dataCache_1__DOT__ways_0_data_symbol0__v0;
        CData/*7:0*/ __VdlyVal__dataCache_1__DOT__ways_0_data_symbol1__v0;
        CData/*0:0*/ __VdlySet__dataCache_1__DOT__ways_0_data_symbol1__v0;
        CData/*7:0*/ __VdlyVal__dataCache_1__DOT__ways_0_data_symbol3__v0;
        CData/*0:0*/ __VdlySet__dataCache_1__DOT__ways_0_data_symbol3__v0;
        SData/*9:0*/ __PVT___zz___05Fzz_decode_IS_RS2_SIGNED_82;
        SData/*15:0*/ __VdfgRegularize_h1463825b_0_35;
        SData/*9:0*/ __PVT__dataCache_1__DOT__dataReadCmd_payload;
        SData/*9:0*/ __PVT__dataCache_1__DOT__dataWriteCmd_payload_address;
        SData/*9:0*/ __VdlyDim0__IBusCachedPlugin_cache__DOT__banks_0__v0;
        SData/*9:0*/ __VdlyDim0__dataCache_1__DOT__ways_0_data_symbol2__v0;
        SData/*9:0*/ __VdlyDim0__dataCache_1__DOT__ways_0_data_symbol0__v0;
        SData/*9:0*/ __VdlyDim0__dataCache_1__DOT__ways_0_data_symbol1__v0;
        SData/*9:0*/ __VdlyDim0__dataCache_1__DOT__ways_0_data_symbol3__v0;
        VL_IN(__PVT__externalResetVector,31,0);
        VL_IN(__PVT__externalInterruptArray,31,0);
        VL_OUT(__PVT__iBusWishbone_ADR,29,0);
        VL_IN(__PVT__iBusWishbone_DAT_MISO,31,0);
        VL_OUT(__PVT__iBusWishbone_DAT_MOSI,31,0);
        VL_OUT(__PVT__dBusWishbone_ADR,29,0);
        VL_IN(__PVT__dBusWishbone_DAT_MISO,31,0);
        VL_OUT(__PVT__dBusWishbone_DAT_MOSI,31,0);
        IData/*31:0*/ __PVT__dataCache_1_io_cpu_execute_address;
        IData/*31:0*/ __PVT___zz_RegFilePlugin_regFile_port0;
        IData/*31:0*/ __PVT___zz_RegFilePlugin_regFile_port1;
        IData/*31:0*/ __PVT__dataCache_1_io_cpu_writeBack_data;
        IData/*31:0*/ __PVT__dataCache_1_io_mem_cmd_payload_address;
        IData/*24:0*/ __PVT___zz___05Fzz_decode_IS_RS2_SIGNED_9;
        IData/*31:0*/ __PVT___zz_decode_RS2;
        IData/*31:0*/ __PVT__decode_RS2;
        IData/*31:0*/ __PVT__decode_RS1;
        IData/*31:0*/ __PVT___zz_decode_RS2_1;
        IData/*31:0*/ __PVT__execute_SRC2;
        IData/*31:0*/ __PVT__execute_SRC1;
        IData/*31:0*/ __PVT__decode_INSTRUCTION_ANTICIPATED;
        IData/*31:0*/ __PVT___zz_decode_RS2_2;
        IData/*31:0*/ lastStageInstruction;
        IData/*31:0*/ lastStagePc;
        IData/*31:0*/ __PVT__IBusCachedPlugin_predictionJumpInterface_payload;
        IData/*31:0*/ __PVT__CsrPlugin_csrMapping_readDataSignal;
        IData/*31:0*/ __PVT__CsrPlugin_csrMapping_writeDataSignal;
        IData/*31:0*/ __PVT__CsrPlugin_jumpInterface_payload;
        IData/*31:0*/ IBusCachedPlugin_fetchPc_pcReg;
        IData/*31:0*/ __PVT__IBusCachedPlugin_fetchPc_pc;
        IData/*31:0*/ __PVT___zz_IBusCachedPlugin_iBusRsp_stages_1_output_m2sPipe_payload;
        IData/*31:0*/ __PVT__IBusCachedPlugin_rspCounter;
        IData/*31:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_address;
        IData/*31:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_rData_data;
        IData/*31:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_address;
        IData/*31:0*/ __PVT__toplevel_dataCache_1_io_mem_cmd_s2mPipe_rData_data;
        IData/*31:0*/ __PVT__DBusCachedPlugin_rspCounter;
        IData/*31:0*/ lastStageRegFileWrite_payload_data;
        IData/*31:0*/ __PVT__execute_FullBarrelShifterPlugin_reversed;
        IData/*31:0*/ __PVT___zz_decode_RS2_3;
        IData/*31:0*/ __PVT__HazardSimplePlugin_writeBackBuffer_payload_data;
        IData/*31:0*/ __PVT__execute_BranchPlugin_branch_src2;
        IData/*29:0*/ __PVT__CsrPlugin_mtvec_base;
        IData/*31:0*/ __PVT__CsrPlugin_mepc;
        IData/*31:0*/ __PVT__CsrPlugin_mtval;
        IData/*31:0*/ __PVT__CsrPlugin_exceptionPortCtrl_exceptionContext_badAddr;
        IData/*16:0*/ __PVT__execute_MulPlugin_aHigh;
    };
    struct {
        IData/*16:0*/ __PVT__execute_MulPlugin_bHigh;
        IData/*31:0*/ __PVT__memory_DivPlugin_rs2;
        VlWide<3>/*64:0*/ __PVT__memory_DivPlugin_accumulator;
        IData/*31:0*/ __PVT__memory_DivPlugin_div_result;
        IData/*31:0*/ __PVT__memory_DivPlugin_div_stage_0_outNumerator;
        IData/*31:0*/ __PVT___zz_memory_DivPlugin_div_result;
        IData/*31:0*/ __PVT__externalInterruptArray_regNext;
        IData/*31:0*/ __PVT___zz_CsrPlugin_csrMapping_readDataInit;
        IData/*31:0*/ __PVT___zz_externalInterrupt;
        IData/*31:0*/ __PVT__decode_to_execute_PC;
        IData/*31:0*/ __PVT__execute_to_memory_PC;
        IData/*31:0*/ __PVT__memory_to_writeBack_PC;
        IData/*31:0*/ __PVT__decode_to_execute_INSTRUCTION;
        IData/*31:0*/ __PVT__execute_to_memory_INSTRUCTION;
        IData/*31:0*/ __PVT__memory_to_writeBack_INSTRUCTION;
        IData/*31:0*/ __PVT__decode_to_execute_FORMAL_PC_NEXT;
        IData/*31:0*/ __PVT__execute_to_memory_FORMAL_PC_NEXT;
        IData/*31:0*/ __PVT__memory_to_writeBack_FORMAL_PC_NEXT;
        IData/*31:0*/ __PVT__decode_to_execute_RS1;
        IData/*31:0*/ __PVT__decode_to_execute_RS2;
        IData/*31:0*/ __PVT__execute_to_memory_MEMORY_STORE_DATA_RF;
        IData/*31:0*/ __PVT__memory_to_writeBack_MEMORY_STORE_DATA_RF;
        IData/*31:0*/ __PVT__execute_to_memory_REGFILE_WRITE_DATA;
        IData/*31:0*/ __PVT__memory_to_writeBack_REGFILE_WRITE_DATA;
        IData/*31:0*/ __PVT__execute_to_memory_SHIFT_RIGHT;
        IData/*31:0*/ __PVT__execute_to_memory_BRANCH_CALC;
        IData/*31:0*/ __PVT__execute_to_memory_MUL_LL;
        IData/*31:0*/ __PVT__iBusWishbone_DAT_MISO_regNext;
        IData/*31:0*/ __PVT__dBusWishbone_DAT_MISO_regNext;
        VlWide<3>/*71:0*/ __PVT__decode_SHIFT_CTRL_string;
        IData/*23:0*/ __PVT__decode_SRC2_CTRL_string;
        VlWide<3>/*95:0*/ __PVT__decode_SRC1_CTRL_string;
        IData/*31:0*/ __PVT__execute_BRANCH_CTRL_string;
        VlWide<3>/*71:0*/ __PVT__memory_SHIFT_CTRL_string;
        VlWide<3>/*71:0*/ __PVT__execute_SHIFT_CTRL_string;
        IData/*23:0*/ __PVT__execute_SRC2_CTRL_string;
        VlWide<3>/*95:0*/ __PVT__execute_SRC1_CTRL_string;
        IData/*31:0*/ __PVT__decode_BRANCH_CTRL_string;
        VlWide<3>/*95:0*/ __PVT__decode_to_execute_SRC1_CTRL_string;
        IData/*23:0*/ __PVT__decode_to_execute_SRC2_CTRL_string;
        VlWide<3>/*71:0*/ __PVT__decode_to_execute_SHIFT_CTRL_string;
        VlWide<3>/*71:0*/ __PVT__execute_to_memory_SHIFT_CTRL_string;
        IData/*31:0*/ __PVT__decode_to_execute_BRANCH_CTRL_string;
        IData/*22:0*/ __VdfgRegularize_h1463825b_0_31;
        IData/*19:0*/ __VdfgRegularize_h1463825b_0_32;
        IData/*31:0*/ __PVT__IBusCachedPlugin_cache__DOT___zz_banks_0_port1;
        IData/*21:0*/ __PVT__IBusCachedPlugin_cache__DOT___zz_ways_0_tags_port1;
        IData/*31:0*/ __PVT__IBusCachedPlugin_cache__DOT__lineLoader_address;
        IData/*31:0*/ __PVT__IBusCachedPlugin_cache__DOT__io_cpu_fetch_data_regNextWhen;
        IData/*31:0*/ __PVT__IBusCachedPlugin_cache__DOT__decodeStage_mmuRsp_physicalAddress;
        IData/*21:0*/ __PVT__dataCache_1__DOT___zz_ways_0_tags_port0;
        IData/*19:0*/ __PVT__dataCache_1__DOT__tagsWriteCmd_payload_data_address;
        IData/*19:0*/ __PVT__dataCache_1__DOT__tagsWriteLastCmd_payload_data_address;
        IData/*31:0*/ __PVT__dataCache_1__DOT__dataWriteCmd_payload_data;
        IData/*31:0*/ __PVT__dataCache_1__DOT__stageB_mmuRsp_physicalAddress;
        IData/*19:0*/ __PVT__dataCache_1__DOT__stageB_tagsReadRsp_0_address;
        IData/*31:0*/ __PVT__dataCache_1__DOT__stageB_dataReadRsp_0;
        IData/*31:0*/ __Vdly__IBusCachedPlugin_rspCounter;
        IData/*31:0*/ __Vdly__DBusCachedPlugin_rspCounter;
        IData/*31:0*/ __VdlyVal__RegFilePlugin_regFile__v0;
        IData/*31:0*/ __VdlyVal__IBusCachedPlugin_cache__DOT__banks_0__v0;
        IData/*21:0*/ __VdlyVal__IBusCachedPlugin_cache__DOT__ways_0_tags__v0;
        IData/*21:0*/ __VdlyVal__dataCache_1__DOT__ways_0_tags__v0;
        QData/*63:0*/ __PVT__CsrPlugin_mcycle;
    };
    struct {
        QData/*63:0*/ __PVT__CsrPlugin_minstret;
        QData/*32:0*/ __PVT__memory_DivPlugin_rs1;
        QData/*32:0*/ __PVT__memory_DivPlugin_div_stage_0_remainderShifted;
        QData/*32:0*/ __PVT__memory_DivPlugin_div_stage_0_remainderMinusDenominator;
        QData/*32:0*/ __PVT___zz_memory_DivPlugin_rs1_1;
        QData/*33:0*/ __PVT__execute_to_memory_MUL_LH;
        QData/*33:0*/ __PVT__execute_to_memory_MUL_HL;
        QData/*33:0*/ __PVT__execute_to_memory_MUL_HH;
        QData/*33:0*/ __PVT__memory_to_writeBack_MUL_HH;
        QData/*51:0*/ __PVT__memory_to_writeBack_MUL_LOW;
        QData/*63:0*/ __Vdly__CsrPlugin_minstret;
        VlUnpacked<IData/*31:0*/, 32> RegFilePlugin_regFile;
        VlUnpacked<IData/*31:0*/, 1024> __PVT__IBusCachedPlugin_cache__DOT__banks_0;
        VlUnpacked<IData/*21:0*/, 128> __PVT__IBusCachedPlugin_cache__DOT__ways_0_tags;
        VlUnpacked<IData/*21:0*/, 128> __PVT__dataCache_1__DOT__ways_0_tags;
        VlUnpacked<CData/*7:0*/, 1024> __PVT__dataCache_1__DOT__ways_0_data_symbol0;
        VlUnpacked<CData/*7:0*/, 1024> __PVT__dataCache_1__DOT__ways_0_data_symbol1;
        VlUnpacked<CData/*7:0*/, 1024> __PVT__dataCache_1__DOT__ways_0_data_symbol2;
        VlUnpacked<CData/*7:0*/, 1024> __PVT__dataCache_1__DOT__ways_0_data_symbol3;
    };

    // INTERNAL VARIABLES
    Vsim__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsim_VexRiscv(Vsim__Syms* symsp, const char* v__name);
    ~Vsim_VexRiscv();
    VL_UNCOPYABLE(Vsim_VexRiscv);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
